### ISSUE TITLE
Chapter -- What is Trove?

### ISSUE THREAD

**Issue by wragge** [wragge/trove-data-guide#8]
## Trove is:

- an aggregation of collection metadata from Australian GLAM and research organisations (includes pre-aggregated content through Libraries Australia as well as individually harvested collections)
- a repository of digitised content from the NLA and partners, includes:
    - newspapers
    - journals and magazines
    - books
    - ephemera
    - photographs
    - maps
    - manuscripts
- an archive of Australian web content from 1996 onwards
- born-digital publications submitted via the electronic legal deposit scheme (access may be restricted)
- a platform for user engagement via tags, comments, lists, and OCR corrections
- a series of APIs for delivering machine-actionable data

## Some basic concepts:

- metadata vs digital objects
- works and versions
- categories and zones
- NLA identifiers

**Comment by mraadgev** [comment]
FYI Tim, Libraries Australia is still standalone, but within the NLA it's all been rolled in under Trove, and will eventually be rebranded
